export const colors = {
  bg: "#f5f5f7",
  surface: "#ffffff",
  border: "rgba(0,0,0,0.08)",
  borderStrong: "#e0e0e5",
  text: "#1d1d1f",
  textSecondary: "#86868b",
  blue: "#0071e3",
  blueLight: "#0071e322",
  blueBorder: "#0071e340",
  green: "#34c759",
  greenLight: "#34c75918",
  orange: "#ff9500",
  orangeLight: "#ff950018",
  red: "#ff3b30",
  redLight: "#ff3b3018",
};

export const fonts = {
  base: "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Helvetica Neue', sans-serif",
  mono: "SF Mono, Monaco, monospace",
};

export const radius = {
  sm: 8,
  md: 10,
  lg: 14,
  xl: 18,
};

export const S = {
  page: {
    fontFamily: fonts.base,
    color: colors.text,
    maxWidth: 1100,
  },
  card: {
    background: colors.surface,
    borderRadius: radius.xl,
    padding: 28,
    boxShadow: "0 2px 20px rgba(0,0,0,0.06)",
    border: "1px solid rgba(0,0,0,0.05)",
    marginBottom: 20,
  },
  label: {
    fontSize: 12,
    fontWeight: 600,
    color: colors.textSecondary,
    letterSpacing: "0.3px",
    textTransform: "uppercase",
    marginBottom: 10,
    display: "block",
  },
  input: {
    padding: "9px 14px",
    borderRadius: radius.md,
    border: `1px solid ${colors.borderStrong}`,
    fontSize: 14,
    fontFamily: fonts.base,
    outline: "none",
    background: colors.bg,
    width: "100%",
    boxSizing: "border-box",
  },
  textarea: {
    padding: "10px 14px",
    borderRadius: radius.md,
    border: `1px solid ${colors.borderStrong}`,
    fontSize: 14,
    fontFamily: fonts.base,
    outline: "none",
    background: colors.bg,
    width: "100%",
    boxSizing: "border-box",
    resize: "vertical",
    minHeight: 80,
  },
  btn: (color = "#0071e3", disabled = false) => ({
    padding: "9px 18px",
    borderRadius: radius.md,
    border: "none",
    background: disabled ? colors.borderStrong : color,
    color: disabled ? colors.textSecondary : "#ffffff",
    fontSize: 13,
    fontWeight: 500,
    cursor: disabled ? "not-allowed" : "pointer",
    fontFamily: fonts.base,
  }),
  chip: (active) => ({
    padding: "7px 16px",
    borderRadius: 20,
    border: `1.5px solid ${active ? colors.blue : colors.borderStrong}`,
    background: active ? colors.blueLight : colors.surface,
    color: active ? colors.blue : colors.text,
    fontSize: 13,
    fontWeight: active ? 600 : 400,
    cursor: "pointer",
    fontFamily: fonts.base,
  }),
  tab: (active) => ({
    padding: "8px 20px",
    borderRadius: radius.md,
    border: "none",
    background: active ? colors.surface : "transparent",
    color: active ? colors.text : colors.textSecondary,
    fontSize: 14,
    fontWeight: active ? 500 : 400,
    cursor: "pointer",
    fontFamily: fonts.base,
    boxShadow: active ? "0 1px 4px rgba(0,0,0,0.1)" : "none",
  }),
};